# https://quarto-tdg.org/yaml.html
project:
  type: website
  output-dir: docs

# tell quarto to read the generated sidebar
# metadata-files:
#   - reference/_sidebar.yml

website:
  title: "globalign"
  description: "Global Sequence Alignment"
  bread-crumbs: false
  page-navigation: true
  back-to-top-navigation: false
  # sidebar:
  #   style: "docked"
  #   contents:
  #     - section: "Tutorial"
  #       contents:
  #         - reference/tutorial.qmd
  #     - section: "Reference"
  #       contents:
  #         - reference/index.qmd
  navbar:
    tools:
      - icon: github
        href: https://github.com/iamgiddyaboutgit/globalign
    search: true
    left:
      - text: Home
        href: reference/index.qmd
      - text: Tutorial
        href: reference/tutorial.qmd
      - text: Documentation
        href: reference/docs/index.qmd

format:
  html:
    embed-resources: true
    theme: reference/darkly.scss
    fontsize: 1.0em
    toc: true
    toc-location: right
    echo: false
    code-overflow: wrap

quartodoc:
  style: pkgdown
  parser: google
  package: globalign
  dir: reference/docs
  sections:
    - title: "Documentation"
      contents: 
        - start
        - globaligner
        - conclude


      